### ISSUE TITLE
Off-By-One preventing running

### ISSUE THREAD

**Issue by anirudhRowjee** [Samyak2/toipe#1]
Hello!

I installed with 
```
$ cargo install toipe
```
and tried to run it, but got the following error - 
![2022-01-10_20-19](https://user-images.githubusercontent.com/42117791/148785737-68d67d03-c231-497c-80a1-27efb6bb26fa.png)

**Comment by Samyak2** [comment]
@anirudhRowjee can you try running it from the latest main branch? This happens because some systems have the word list sorted in an order I did not expect :)

**Comment by anirudhRowjee** [comment]
on it!

**Comment by anirudhRowjee** [comment]
works when I clone and run it from scratch. Looks amazing!

**Comment by Samyak2** [comment]
Thank you!

I have released [v0.1.1](https://github.com/Samyak2/toipe/releases/tag/v0.1.1) on crates.io fixing this. Should be fixed when installed with `cargo install toipe` too.
