### ISSUE TITLE
Minor bug

### ISSUE THREAD

**Issue by gravitywolfLaCanneAPeche** [Samyak2/toipe#15]
I found a very minor bug (which don't influence the gameplay or anything else) in the program :
If you write a single word, and then press `ctrl` + `c`, you can get like more than 2000wpm, and the program says that you took 0s for 30 words.

**Comment by Samyak2** [comment]
Yes, I noticed that too. I was thinking of directly exiting on ctrl+c instead of showing the results screen. What do you think of that?

**Comment by gravitywolfLaCanneAPeche** [comment]
Seems a good solution
