### ISSUE TITLE
Add shortcut for deleting the last word

### ISSUE THREAD

**Issue by Samyak2** [Samyak2/toipe#18]
# What and why?

A shortcut to delete the last typed word would be nice. ctrl-w and ctrl-backspace can be used for this.

# How?

TODO

# Context

Suggestion from reddit: https://www.reddit.com/r/unixporn/comments/tw84a3/comment/i3endiw/

**Comment by Samyak2** [comment]
ctrl-backspace cannot be implemented because termion only supports [a char with the ctrl modifier](https://docs.rs/termion/latest/termion/event/enum.Key.html#variant.Ctrl)

**Comment by codevion** [comment]
Awesome. Happy to see this.
