### ISSUE TITLE
ctrl+h to backspace

### ISSUE THREAD

**Issue by bcatalfo** [Samyak2/toipe#50]
Can you add ctrl+h to backspace? I use ctrl+h to backspace on my terminal and in my terminal based editors. Thanks.

**Comment by idevtier** [comment]
Hey! I'm planning to PR with better C-w experience, but firstly I can try to add support of C-h for you

**Comment by Samyak2** [comment]
Great suggestion! Thank you @idevtier for taking this up 😄
